const crypto=require('crypto');
function json(statusCode,body){return{statusCode,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(body)}}
function verify(token,secret){if(!token||!secret)return null;const [e,s]=token.split('.');if(!e||!s)return null;const x=crypto.createHmac('sha256',secret).update(e).digest('base64url');const a=Buffer.from(s),b=Buffer.from(x);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const p=JSON.parse(Buffer.from(e,'base64url').toString('utf8'));return p.exp>Date.now()?p:null}catch{return null}}
async function supabase(path,opt={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase server connection is not configured.');const r=await fetch(`${url}/rest/v1/${path}`,{...opt,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:opt.prefer||'',...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:(d?.message||`Supabase error ${r.status}`));return d}
function hideId(name){return'catalog-hide-'+crypto.createHash('sha1').update(String(name).toLowerCase()).digest('hex').slice(0,16)}
exports.handler=async event=>{const session=verify((event.headers.authorization||'').replace(/^Bearer\s+/i,''),process.env.SESSION_SECRET);if(!session)return json(401,{error:'Session expired. Please sign in again.'});const papa=session.name==='Papa'&&session.role==='admin';try{
if(event.httpMethod==='GET'){const rows=await supabase('medication_entries?id=like.catalog-%25&deleted=eq.false&order=entry_timestamp.asc&select=id,note,medications');const hidden=[],items=[];(rows||[]).forEach(r=>{const note=String(r.note||'');if(r.id.startsWith('catalog-hide-')&&note.startsWith('__HIDE__:')){hidden.push(note.slice(9));return}const name=note;if(name)items.push({id:r.id,name,dose:Array.isArray(r.medications)&&r.medications[0]?r.medications[0].dose||'':''})});return json(200,{items,hidden_names:hidden,can_manage:papa})}
if(event.httpMethod==='POST'){if(!papa)return json(403,{error:'Papa access required.'});let b;try{b=JSON.parse(event.body||'{}')}catch{return json(400,{error:'Invalid request'})}const name=String(b.name||'').trim(),dose=String(b.dose||'').trim();if(!name)return json(400,{error:'Enter medication name.'});if(b.action==='restore'){await supabase(`medication_entries?id=eq.${encodeURIComponent(hideId(name))}`,{method:'DELETE',prefer:'return=minimal'});return json(200,{ok:true,restored:name})}const now=new Date(),id=`catalog-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`;const row={id,user_id:null,entry_timestamp:now.toISOString(),entry_date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5),medications:[{name:'__CATALOG__',dose}],temp:null,temp_unit:'°C',note:name,nurse:'Papa',updated_at:now.toISOString(),deleted:false};await supabase('medication_entries',{method:'POST',body:JSON.stringify(row),prefer:'return=minimal'});await supabase(`medication_entries?id=eq.${encodeURIComponent(hideId(name))}`,{method:'DELETE',prefer:'return=minimal'});return json(200,{ok:true,item:{id,name,dose}})}
if(event.httpMethod==='DELETE'){if(!papa)return json(403,{error:'Papa access required.'});let b;try{b=JSON.parse(event.body||'{}')}catch{return json(400,{error:'Invalid request'})}const id=String(b.id||''),name=String(b.name||'').trim();if(id.startsWith('catalog-')&&!id.startsWith('catalog-hide-')){await supabase(`medication_entries?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({deleted:true,updated_at:new Date().toISOString()}),prefer:'return=minimal'});return json(200,{ok:true})}if(name){const now=new Date(),hid=hideId(name),row={id:hid,user_id:null,entry_timestamp:now.toISOString(),entry_date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5),medications:[{name:'__HIDE__',dose:''}],temp:null,temp_unit:'°C',note:`__HIDE__:${name}`,nurse:'Papa',updated_at:now.toISOString(),deleted:false};await supabase('medication_entries?on_conflict=id',{method:'POST',body:JSON.stringify(row),prefer:'resolution=merge-duplicates,return=minimal'});return json(200,{ok:true,hidden:name})}return json(400,{error:'Invalid catalog item.'})}
return json(405,{error:'Method not allowed'})}catch(e){return json(500,{error:e.message||'Server error'})}};