(() => {
  const style=document.createElement('style');
  style.textContent=`
  .med-manager-btn{display:none;width:100%;margin-top:6px;border:1px solid #b9dfda;border-radius:12px;background:#effaf8;color:#087477;padding:9px;font-weight:900}.med-manager-btn.show{display:block}
  .med-manager-backdrop{display:none;position:fixed;inset:0;z-index:9500;background:#0009;padding:18px;align-items:center;justify-content:center}.med-manager-backdrop.open{display:flex}
  .med-manager{width:min(620px,100%);max-height:86vh;background:#fff;border-radius:22px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 90px #0008}.med-manager-head{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;background:#0b2b24;color:#fff}.med-manager-head button{border:0;border-radius:999px;background:#ffffff20;color:#fff;padding:8px 12px;font-weight:900}.med-manager-body{padding:14px;overflow:auto}.med-add-grid{display:grid;grid-template-columns:1.2fr 1fr auto;gap:7px;padding-bottom:12px;border-bottom:1px solid #e8f0ef}.med-add-grid input{margin:0}.med-add-grid button{border:0;border-radius:11px;background:#0aa5a3;color:#fff;padding:0 15px;font-weight:900}.med-list-title{display:flex;align-items:center;justify-content:space-between;margin:13px 2px 8px}.med-list-title strong{font-size:14px}.med-list-count{font-size:11px;color:#71888c;background:#eff6f5;border-radius:999px;padding:4px 7px}.med-custom-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:9px 10px;border:1px solid #e1ecea;border-radius:11px;margin-bottom:7px;background:#fbfefe}.med-custom-name{font-weight:900;font-size:14px}.med-custom-dose{font-size:11px;color:#71888c;margin-top:2px}.med-custom-delete{width:34px;height:34px;border:0;border-radius:10px;background:#fff0f0;color:#a22;display:grid;place-items:center;font-size:18px}.med-empty{padding:22px;text-align:center;color:#71888c}
  #history .temp{font-size:11px!important;line-height:1!important;padding:5px 6px!important;min-width:38px!important;width:38px!important;text-align:center!important;white-space:nowrap!important}
  @media(max-width:600px){.med-add-grid{grid-template-columns:1fr}.med-add-grid button{padding:11px}.med-manager{max-height:90vh}#history .temp{font-size:10px!important;min-width:34px!important;width:34px!important;padding:4px 5px!important}}
  `;document.head.appendChild(style);

  function compactTemps(){document.querySelectorAll('#history .temp').forEach(el=>{const m=el.textContent.match(/-?\d+(?:\.\d+)?/);if(m)el.textContent=m[0]})}
  function currentName(){try{return JSON.parse(localStorage.getItem('rithyna-secure-session-v23')||'null')?.name||''}catch{return''}}
  function papa(){return currentName()==='Papa'}
  function signed(){return document.getElementById('gate')?.classList.contains('hide')}
  const baseCatalog=(typeof catalog!=='undefined'?catalog:[]).map(x=>[x[0],x[1]||'']);
  let customItems=[],hiddenNames=[];

  function rebuildCatalog(){if(typeof catalog==='undefined')return;const hidden=new Set(hiddenNames.map(x=>String(x).toLowerCase()));const next=baseCatalog.filter(x=>!hidden.has(String(x[0]).toLowerCase()));customItems.forEach(x=>{if(!next.some(m=>m[0].toLowerCase()===x.name.toLowerCase()))next.push([x.name,x.dose||''])});catalog.splice(0,catalog.length,...next);document.querySelectorAll('.medrow select').forEach(sel=>{const oldText=sel.options[sel.selectedIndex]?.textContent||'';sel.innerHTML='';catalog.forEach((m,i)=>sel.add(new Option(m[0],i)));const idx=catalog.findIndex(m=>m[0]===oldText);sel.value=String(idx>=0?idx:0);sel.dispatchEvent(new Event('change',{bubbles:true}))})}
  async function loadCatalog(){if(!signed())return;try{const j=await request('medication-catalog');customItems=j.items||[];hiddenNames=j.hidden_names||[];rebuildCatalog();renderList()}catch(e){console.warn(e)}}
  function ensureUI(){const addBtn=document.getElementById('add');if(addBtn&&!document.getElementById('manageMedicationBtn')){const b=document.createElement('button');b.type='button';b.id='manageMedicationBtn';b.className='med-manager-btn';b.textContent='⚙ Manage medication list';b.onclick=openManager;addBtn.insertAdjacentElement('afterend',b)}if(!document.getElementById('medManagerBackdrop')){const bd=document.createElement('div');bd.id='medManagerBackdrop';bd.className='med-manager-backdrop';bd.innerHTML=`<div class="med-manager"><div class="med-manager-head"><div><strong>Manage Medication List</strong><div style="font-size:11px;color:#c9e4df;margin-top:2px">Papa can add or remove medications</div></div><button id="medManagerClose">Close</button></div><div class="med-manager-body"><div class="med-add-grid"><input id="newMedName" placeholder="Medication name"><input id="newMedDose" placeholder="Default dose"><button id="newMedAdd">＋ Add</button></div><div class="med-list-title"><strong>Current medication list</strong><span id="medListCount" class="med-list-count"></span></div><div id="medCustomList"></div></div></div>`;bd.onclick=e=>{if(e.target===bd)closeManager()};document.body.appendChild(bd);document.getElementById('medManagerClose').onclick=closeManager;document.getElementById('newMedAdd').onclick=addMedication}updateVisibility()}
  function updateVisibility(){const b=document.getElementById('manageMedicationBtn');if(b)b.classList.toggle('show',signed()&&papa())}
  function openManager(){if(!papa())return;document.getElementById('medManagerBackdrop')?.classList.add('open');loadCatalog()}
  function closeManager(){document.getElementById('medManagerBackdrop')?.classList.remove('open')}
  function visibleItems(){const hidden=new Set(hiddenNames.map(x=>String(x).toLowerCase()));const built=baseCatalog.filter(x=>!hidden.has(String(x[0]).toLowerCase())).map(x=>({name:x[0],dose:x[1]||'',builtIn:true}));const custom=customItems.map(x=>({...x,builtIn:false}));const seen=new Set();return [...built,...custom].filter(x=>{const k=x.name.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
  function renderList(){const box=document.getElementById('medCustomList');if(!box)return;const items=visibleItems();const count=document.getElementById('medListCount');if(count)count.textContent=`${items.length} medications`;if(!items.length){box.innerHTML='<div class="med-empty">No medications in the list.</div>';return}box.innerHTML=items.map((x,i)=>`<div class="med-custom-row"><div><div class="med-custom-name"></div><div class="med-custom-dose"></div></div><button class="med-custom-delete" data-i="${i}" title="Remove">×</button></div>`).join('');box.querySelectorAll('.med-custom-name').forEach((e,i)=>e.textContent=items[i].name);box.querySelectorAll('.med-custom-dose').forEach((e,i)=>e.textContent=items[i].dose||'No default dose');box.querySelectorAll('.med-custom-delete').forEach(b=>b.onclick=()=>removeMedication(items[+b.dataset.i]))}
  async function addMedication(){if(!papa())return;const n=document.getElementById('newMedName'),d=document.getElementById('newMedDose'),name=n.value.trim(),dose=d.value.trim();if(!name)return alert('Enter medication name.');const btn=document.getElementById('newMedAdd');btn.disabled=true;btn.textContent='Adding…';try{await request('medication-catalog',{method:'POST',body:JSON.stringify({name,dose})});n.value='';d.value='';await loadCatalog()}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='＋ Add'}}
  async function removeMedication(item){if(!papa()||!item)return;if(!confirm(`Remove ${item.name} from the medication list?`))return;try{if(item.builtIn){await request('medication-catalog',{method:'DELETE',body:JSON.stringify({name:item.name})});hiddenNames.push(item.name)}else{await request('medication-catalog',{method:'DELETE',body:JSON.stringify({id:item.id,name:item.name})});customItems=customItems.filter(x=>x.id!==item.id)}rebuildCatalog();renderList()}catch(e){alert(e.message)}}
  ensureUI();compactTemps();const history=document.getElementById('history');if(history)new MutationObserver(()=>compactTemps()).observe(history,{childList:true,subtree:true});const gate=document.getElementById('gate');if(gate)new MutationObserver(()=>{updateVisibility();if(signed())loadCatalog()}).observe(gate,{attributes:true,attributeFilter:['class']});setInterval(updateVisibility,1000);if(signed())loadCatalog();
})();