(()=>{
  const style=document.createElement('style');style.textContent=`.med-manager-btn{display:block;width:100%;margin-top:6px;border:1px solid #b9dfda;border-radius:12px;background:#effaf8;color:#087477;padding:9px;font-weight:900}.med-manager-backdrop{display:none;position:fixed;inset:0;z-index:9500;background:#0009;padding:18px;align-items:center;justify-content:center}.med-manager-backdrop.open{display:flex}.med-manager{width:min(620px,100%);max-height:86vh;background:#fff;border-radius:22px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 90px #0008}.med-manager-head{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;background:#0b2b24;color:#fff}.med-manager-head button{border:0;border-radius:999px;background:#ffffff20;color:#fff;padding:8px 12px;font-weight:900}.med-manager-body{padding:14px;overflow:auto}.med-add-grid{display:grid;grid-template-columns:1.2fr 1fr auto;gap:7px;padding-bottom:12px;border-bottom:1px solid #e8f0ef}.med-add-grid button{border:0;border-radius:11px;background:#0aa5a3;color:#fff;padding:0 15px;font-weight:900}.med-custom-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:9px 10px;border:1px solid #e1ecea;border-radius:11px;margin-bottom:7px;background:#fbfefe}.med-custom-row.inactive{opacity:.55;background:#f1f3f3}.med-actions{display:flex;gap:6px}.med-edit,.med-toggle{height:34px;border:0;border-radius:999px;font-weight:900;font-size:11px}.med-edit{background:#eef5ff;color:#315d91}.med-toggle{background:#e7f6ef;color:#147451}.med-edit-panel{display:none;grid-template-columns:1fr 1fr auto auto;gap:6px;margin:0 0 8px;padding:9px;background:#effaf8;border-radius:11px}.med-edit-panel.open{display:grid}@media(max-width:600px){.med-add-grid,.med-edit-panel{grid-template-columns:1fr}.med-add-grid button{padding:11px}}`;document.head.appendChild(style);
  function currentName(){try{return JSON.parse(localStorage.getItem('rithyna-secure-session-v23')||'null')?.name||document.getElementById('recorded')?.value||''}catch{return document.getElementById('recorded')?.value||''}}function papa(){return currentName()==='Papa'}
  const baseCatalog=(typeof catalog!=='undefined'?catalog:[]).map(x=>[x[0],x[1]||'']);let customItems=[],hiddenNames=[],edits=[];function editFor(n){return edits.find(e=>String(e.original).toLowerCase()===String(n).toLowerCase())}function allItems(){const hidden=new Set(hiddenNames.map(x=>String(x).toLowerCase()));const built=baseCatalog.map(x=>{const e=editFor(x[0]);return{name:e?.name||x[0],dose:e?.dose??x[1]||'',original:x[0],inactive:hidden.has(String(x[0]).toLowerCase())}});const custom=customItems.map(x=>{const e=editFor(x.name);return{name:e?.name||x.name,dose:e?.dose??x.dose||'',original:x.name,inactive:hidden.has(String(x.name).toLowerCase())}});const seen=new Set();return [...built,...custom].filter(x=>{const k=x.name.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
  function rebuildCatalog(){if(typeof catalog==='undefined')return;catalog.splice(0,catalog.length,...allItems().filter(x=>!x.inactive).map(x=>[x.name,x.dose||'']))}
  async function loadCatalog(){try{const j=await request('medication-catalog');customItems=j.items||[];hiddenNames=j.hidden_names||[];edits=j.edits||[];rebuildCatalog();renderList()}catch(e){console.warn(e)}}
  function ensureUI(){const addBtn=document.getElementById('add');if(addBtn&&!document.getElementById('manageMedicationBtn')){const b=document.createElement('button');b.type='button';b.id='manageMedicationBtn';b.className='med-manager-btn';b.textContent='⚙ Manage medication list';b.onclick=openManager;addBtn.insertAdjacentElement('afterend',b)}if(!document.getElementById('medManagerBackdrop')){const bd=document.createElement('div');bd.id='medManagerBackdrop';bd.className='med-manager-backdrop';bd.innerHTML=`<div class="med-manager"><div class="med-manager-head"><strong>Manage Medication List</strong><button id="medManagerClose">Close</button></div><div class="med-manager-body"><div class="med-add-grid"><input id="newMedName" placeholder="Medication name"><input id="newMedDose" placeholder="Default dose"><button id="newMedAdd">＋ Add</button></div><div id="medCustomList" style="margin-top:12px"></div></div></div>`;document.body.appendChild(bd);bd.onclick=e=>{if(e.target===bd)bd.classList.remove('open')};document.getElementById('medManagerClose').onclick=()=>bd.classList.remove('open');document.getElementById('newMedAdd').onclick=addMedication}}
  function openManager(){document.getElementById('medManagerBackdrop')?.classList.add('open');loadCatalog()}
  function renderList(){const box=document.getElementById('medCustomList');if(!box)return;const items=allItems();box.innerHTML=items.map((x,i)=>`<div class="med-custom-row ${x.inactive?'inactive':''}"><div><b></b><div style="font-size:11px;color:#71888c"></div></div><div class="med-actions"><button class="med-edit" data-i="${i}">Edit</button><button class="med-toggle" data-i="${i}">${x.inactive?'Activate':'Active'}</button></div></div><div class="med-edit-panel" id="medEditPanel${i}"><input class="med-edit-name"><input class="med-edit-dose"><button class="med-edit-save">Save</button><button class="med-edit-cancel">Cancel</button></div>`).join('');box.querySelectorAll('.med-custom-row').forEach((r,i)=>{r.querySelector('b').textContent=items[i].name;r.querySelector('div div').textContent=items[i].dose||'No default dose'});box.querySelectorAll('.med-toggle').forEach(b=>b.onclick=()=>toggleMedication(items[+b.dataset.i]));box.querySelectorAll('.med-edit').forEach(b=>b.onclick=()=>openEdit(items,+b.dataset.i))}
  function openEdit(items,i){const item=items[i],p=document.getElementById('medEditPanel'+i);p.classList.add('open');p.querySelector('.med-edit-name').value=item.name;p.querySelector('.med-edit-dose').value=item.dose||'';p.querySelector('.med-edit-cancel').onclick=()=>p.classList.remove('open');p.querySelector('.med-edit-save').onclick=async()=>{const name=p.querySelector('.med-edit-name').value.trim(),dose=p.querySelector('.med-edit-dose').value.trim();if(!name)return;await request('medication-catalog',{method:'PATCH',body:JSON.stringify({original:item.original,name,dose})});await loadCatalog()}}
  async function addMedication(){const n=document.getElementById('newMedName'),d=document.getElementById('newMedDose'),name=n.value.trim(),dose=d.value.trim();if(!name)return alert('Enter medication name.');await request('medication-catalog',{method:'POST',body:JSON.stringify({name,dose})});n.value='';d.value='';await loadCatalog()}
  async function toggleMedication(item){if(item.inactive)await request('medication-catalog',{method:'POST',body:JSON.stringify({action:'restore',name:item.original})});else await request('medication-catalog',{method:'DELETE',body:JSON.stringify({name:item.original})});await loadCatalog()}
  ensureUI();if(papa())loadCatalog();setTimeout(()=>{ensureUI();if(papa())loadCatalog()},600);
})();